server {
    listen 80;
    listen [::]:80;
    server_name rank.viewflow.io;

    location /.well-known/acme-challenge/ {
        root /srv/rank-viewflow-io/.letsencrypt;
    }
    location / {
        return 301 https://rank.viewflow.io$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name rank.viewflow.io;

    ssl_certificate     /etc/letsencrypt/live/rank.viewflow.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/rank.viewflow.io/privkey.pem;

    root /srv/rank-viewflow-io/public;
    index index.html;
    add_header Cross-Origin-Opener-Policy same-origin always;
    add_header Cross-Origin-Embedder-Policy require-corp always;

    location /.well-known/acme-challenge/ {
        root /srv/rank-viewflow-io/.letsencrypt;
    }
    location / {
        try_files $uri $uri/ =404;
    }
    location ~* \.(?:css|js|png|jpg|jpeg|gif|svg|webp|ico|woff2?)$ {
        expires 7d;
        add_header Cache-Control "public";
        add_header Cross-Origin-Opener-Policy same-origin always;
        add_header Cross-Origin-Embedder-Policy require-corp always;
    }
}
