import { type Module, type AstNode, type CstNode, type GrammarAST, type ValueType, type ParserOptions, DefaultValueConverter, inject, createLangiumParser, createCompletionParser } from 'langium';
import { LLStarLookaheadStrategy } from 'chevrotain-allstar';
import { groupExpressions, type GroupingOptions } from './expression-grouping.js';
import { normalizePrimaryApplications } from './primary-applications.js';
import { isProgram } from './generated/ast.js';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { RankGeneratedModule, RankGeneratedSharedModule } from './generated/module.js';
import { RankValidator, registerValidationChecks } from './rank-validator.js';

/** An integer written with an exponent (`4e6`, `2E+3`) is the digits followed by that many zeros. */
class RankValueConverter extends DefaultValueConverter {
    protected override runConverter(rule: GrammarAST.AbstractRule, input: string, cstNode: CstNode): ValueType {
        const exponent = rule.name === 'INTEGER' ? /^([0-9]+)[eE]\+?([0-9]+)$/.exec(input) : undefined;
        if (exponent) {
            if (Number(exponent[2]) > 10_000) throw new Error('Integer exponent is too large');
            return BigInt(exponent[1] + '0'.repeat(Number(exponent[2])));
        }
        return super.runConverter(rule, input, cstNode);
    }
}

/**
 * Declaration of custom services - add your own service classes here.
 */
export type RankAddedServices = {
    validation: {
        RankValidator: RankValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type RankServices = LangiumServices & RankAddedServices

/** Keep adaptive LL(*) prediction, but bound the token paths enumerated for syntax errors. */
function withBoundedErrorLookahead(services: RankServices, incomplete = false): RankServices {
    const parser: RankServices['parser'] = Object.create(services.parser);
    Object.defineProperty(parser, 'ParserConfig', { value: {
        ...services.parser.ParserConfig,
        maxLookahead: 1,
        lookaheadStrategy: new LLStarLookaheadStrategy({ incomplete,
            logging: services.LanguageMetaData.mode === 'production' ? () => {} : undefined }),
    } });
    return { ...services, parser };
}

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const RankModule: Module<RankServices, PartialLangiumServices & RankAddedServices> = {
    parser: {
        ValueConverter: () => new RankValueConverter(),
        LangiumParser: services => {
            // Enumerating three-token error paths for an unfinished `array` blocks typing for hundreds of ms.
            const parser = createLangiumParser(withBoundedErrorLookahead(services));
            const parse = parser.parse.bind(parser);
            parser.parse = <T extends AstNode>(input: string, options?: ParserOptions) => {
                const result = parse<T>(input, options);
                if (!result.lexerErrors.length && !result.parserErrors.length && isProgram(result.value)) {
                    normalizePrimaryApplications(result.value);
                    groupExpressions(result.value, options as GroupingOptions);
                }
                return result;
            };
            return parser;
        },
        CompletionParser: services => createCompletionParser(withBoundedErrorLookahead(services, true)),
    },
    validation: {
        RankValidator: services => new RankValidator(services)
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createRankServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Rank: RankServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        RankGeneratedSharedModule
    );
    const Rank = inject(
        createDefaultModule({ shared }),
        RankGeneratedModule,
        RankModule
    );
    shared.ServiceRegistry.register(Rank);
    registerValidationChecks(Rank);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, Rank };
}
