import { type Module, type AstNode, type ParserOptions, inject, createLangiumParser } from 'langium';
import { groupExpressions, type GroupingOptions } from './expression-grouping.js';
import { normalizePrimaryApplications } from './primary-applications.js';
import { isProgram } from './generated/ast.js';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { RankGeneratedModule, RankGeneratedSharedModule } from './generated/module.js';
import { RankValidator, registerValidationChecks } from './rank-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type RankAddedServices = {
    validation: {
        RankValidator: RankValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type RankServices = LangiumServices & RankAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const RankModule: Module<RankServices, PartialLangiumServices & RankAddedServices> = {
    parser: {
        LangiumParser: services => {
            const parser = createLangiumParser(services);
            const parse = parser.parse.bind(parser);
            parser.parse = <T extends AstNode>(input: string, options?: ParserOptions) => {
                const result = parse<T>(input, options);
                if (!result.lexerErrors.length && !result.parserErrors.length && isProgram(result.value)) {
                    normalizePrimaryApplications(result.value);
                    groupExpressions(result.value, options as GroupingOptions);
                }
                return result;
            };
            return parser;
        },
    },
    validation: {
        RankValidator: () => new RankValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createRankServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Rank: RankServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        RankGeneratedSharedModule
    );
    const Rank = inject(
        createDefaultModule({ shared }),
        RankGeneratedModule,
        RankModule
    );
    shared.ServiceRegistry.register(Rank);
    registerValidationChecks(Rank);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, Rank };
}
